/**
 * Generates assets/opencomms.ico (multi-resolution, uncompressed BMP frames)
 * AND src/cli/icon-base64.ts (the same bytes embedded in the exe so the
 * install wizard can drop icon.ico next to the installed binary for shortcut
 * IconLocation). Pure Node, zero dependencies. Run: node scripts/make-icon.mjs
 *
 * Design: dark rounded-square tile (#1c1c1c, #333333 border) with a white
 * (#e8e8e8) chat-bubble ring with a lower-left tail and a green (#7fa878)
 * status dot - the console palette from the UI spec, readable at 16px.
 */
import { mkdirSync, writeFileSync, statSync } from "node:fs"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const SIZES = [16, 32, 48, 64, 128, 256]

/** "#rrggbbaa" -> [B, G, R, A] (BGRA byte order for 32bpp BMP frames). */
function hex(h) {
  return [
    Number.parseInt(h.slice(5, 7), 16),
    Number.parseInt(h.slice(7, 9), 16),
    Number.parseInt(h.slice(1, 3), 16),
    Number.parseInt(h.slice(3, 5), 16),
  ]
}

const TILE = hex("#1c1c1cff")
const BORDER = hex("#333333ff")
const TEXT = hex("#e8e8e8ff")
const GOOD = hex("#7fa878ff")
const TRANSPARENT = [0, 0, 0, 0]

/** Rounded-rect hit test with corner radius r over [x0,y0]..[x1,y1]. */
function inRoundedRect(x, y, x0, y0, x1, y1, r) {
  if (x < x0 || y < y0 || x > x1 || y > y1) return false
  const cx = x < x0 + r ? x0 + r : x > x1 - r ? x1 - r : x
  const cy = y < y0 + r ? y0 + r : y > y1 - r ? y1 - r : y
  return (x - cx) ** 2 + (y - cy) ** 2 <= r * r
}

function drawFrame(S) {
  const px = Buffer.alloc(S * S * 4)
  const put = (x, y, c) => {
    if (x < 0 || y < 0 || x >= S || y >= S) return
    const i = (y * S + x) * 4
    for (let k = 0; k < 4; k++) px[i + k] = c[k]
  }

  const inset = S >= 32 ? Math.max(1, Math.round(S * 0.03)) : 0
  const corner = Math.max(2, Math.round(S * 0.18))
  for (let y = 0; y < S; y++) {
    for (let x = 0; x < S; x++) {
      if (inset === 0) {
        if (inRoundedRect(x, y, 0, 0, S - 1, S - 1, corner)) put(x, y, TILE)
        continue
      }
      if (inRoundedRect(x, y, inset, inset, S - 1 - inset, S - 1 - inset, corner)) {
        const isEdge = !inRoundedRect(x, y, inset + 1, inset + 1, S - 2 - inset, S - 2 - inset, corner)
        put(x, y, isEdge ? BORDER : TILE)
      }
    }
  }

  // Chat bubble ring (white) with a small tail toward the lower-left.
  const cx = S / 2
  const cy = S * 0.44
  const rOuter = S * 0.27
  const rInner = S * 0.16
  const tailW = Math.max(1, Math.round(S * 0.09))
  for (let y = 0; y < S; y++) {
    for (let x = 0; x < S; x++) {
      const d = Math.hypot(x - cx, y - cy)
      if (d <= rOuter && d >= rInner) put(x, y, TEXT)
    }
  }
  for (let k = 0; k < tailW; k++) {
    for (let j = 0; j <= k; j++) {
      put(Math.round(cx - rOuter * 0.72) - j, Math.round(cy + rOuter * 0.62) + k, TEXT)
    }
  }

  // Status dot, lower-right (console's Idle green).
  const dcx = S * 0.72
  const dcy = S * 0.76
  const dr = Math.max(1, Math.round(S * 0.09))
  for (let y = 0; y < S; y++) {
    for (let x = 0; x < S; x++) {
      if ((x - dcx) ** 2 + (y - dcy) ** 2 <= dr * dr) put(x, y, GOOD)
    }
  }

  // BMP frame: rows BOTTOM-UP, then an all-zero AND mask (alpha decides).
  const xor = Buffer.alloc(S * S * 4)
  for (let y = 0; y < S; y++) {
    for (let x = 0; x < S; x++) {
      const src = ((S - 1 - y) * S + x) * 4
      px.copy(xor, (y * S + x) * 4, src, src + 4)
    }
  }
  const and = Buffer.alloc(Math.ceil(S / 8) * S)
  const header = Buffer.alloc(40)
  header.writeUInt32LE(40, 0)
  header.writeInt32LE(S, 4)
  header.writeInt32LE(S * 2, 8)
  header.writeUInt16LE(1, 12)
  header.writeUInt16LE(32, 14)
  return Buffer.concat([header, xor, and])
}

function buildIco() {
  const frames = SIZES.map(drawFrame)
  const header = Buffer.alloc(6)
  header.writeUInt16LE(0, 0)
  header.writeUInt16LE(1, 2)
  header.writeUInt16LE(SIZES.length, 4)
  const entries = []
  let offset = 6 + SIZES.length * 16
  SIZES.forEach((S, i) => {
    const e = Buffer.alloc(16)
    e.writeUInt8(S >= 256 ? 0 : S, 0)
    e.writeUInt8(S >= 256 ? 0 : S, 1)
    e.writeUInt16LE(1, 4)
    e.writeUInt16LE(32, 6)
    e.writeUInt32LE(frames[i].length, 8)
    e.writeUInt32LE(offset, 12)
    offset += frames[i].length
    entries.push(e)
  })
  return Buffer.concat([header, ...entries, ...frames])
}

const ico = buildIco()
mkdirSync(join(root, "assets"), { recursive: true })
const icoPath = join(root, "assets", "opencomms.ico")
writeFileSync(icoPath, ico)

// Single-line literal: the base64 is ~370KB and prettier's printer hits a
// stack overflow reformatting a 3.7k-node concat chain.
const wrapped = `"${ico.toString("base64")}"`
const moduleSrc = `/* Generated by scripts/make-icon.mjs - do not edit by hand. */
export const ICON_ICO_BASE64: string =
  ${wrapped}

export function iconIcoBytes(): Uint8Array {
  return Uint8Array.from(Buffer.from(ICON_ICO_BASE64, "base64"))
}
`
mkdirSync(join(root, "src", "cli"), { recursive: true })
writeFileSync(join(root, "src", "cli", "icon-base64.ts"), moduleSrc)
console.log(`opencomms.ico written (${statSync(icoPath).size} bytes, sizes ${SIZES.join("/")})`)
